export const products = [
    {
      id: 1,
      title: "Cool & Cool Adult Alcohol Wipes",
      price: "Rs. 1,137.15",
      oldPrice: "Rs. 1,197.00",
      image: "/home-sales-container-imges/Cool & Cool Adult Alcohol Wipes-1.webp",
      description: "Cool & Cool Adult Alcohol Wipes are perfect for quick cleansing and sanitizing. Ideal for on-the-go hygiene.",
      brand: "Cool & Cool",
      unit: "Pack of 80 Wipes",
      inStock: true,
      rating: 4,
      reviewCount: 95,
      reviews: [
        { name: "Sana Mirza", date: "10 Oct 2024", rating: 5, comment: "Very convenient and effective. Always keep these handy!" },
        { name: "Ali Hassan", date: "18 Oct 2024", rating: 4, comment: "Good quality wipes, nice fragrance." },
      ],
    },
    {
      id: 2,
      title: "Bnb Instant Brightening Tone Up Facial Wash 120ml",
      price: "Rs. 652.50",
      oldPrice: "Rs. 725.00",
      image: "/home-sales-container-imges/Bnb Instant Brightening Tone Up Facial Wash 120ml-2.webp",
      description: "BnB Instant Brightening Tone Up Facial Wash gently cleanses and brightens skin tone instantly with regular use.",
      brand: "BnB",
      unit: "120ml",
      inStock: true,
      rating: 4,
      reviewCount: 142,
      reviews: [
        { name: "Hira Baig", date: "5 Nov 2024", rating: 4, comment: "Skin feels fresh and bright after use." },
        { name: "Zara Khan", date: "12 Nov 2024", rating: 5, comment: "Love this product! Works great on my skin." },
      ],
    },
    {
      id: 3,
      title: "Hemani Pure Coconut Hair Oil 100ml",
      price: "Rs. 213.16",
      oldPrice: "Rs. 236.84",
      image: "/home-sales-container-imges/HEMANI PURE COCONUT HAIR OIL 100ML-3.webp",
      description: "Hemani Pure Coconut Hair Oil nourishes and strengthens hair from root to tip. 100% natural and chemical free.",
      brand: "Hemani",
      unit: "100ml",
      inStock: true,
      rating: 5,
      reviewCount: 230,
      reviews: [
        { name: "Nadia Iqbal", date: "1 Nov 2024", rating: 5, comment: "Amazing oil! Hair feels so soft and shiny." },
        { name: "Usman Tariq", date: "9 Nov 2024", rating: 5, comment: "Pure and natural. Highly recommended." },
      ],
    },
    {
      id: 4,
      title: "Hemani Rose Hand Wash 500ml",
      price: "Rs. 426.31",
      oldPrice: "Rs. 473.68",
      image: "/home-sales-container-imges/Saeed Ghani Organic Rose Water Spray 120ml-5.webp",
      description: "Hemani Rose Hand Wash with natural rose extracts keeps hands clean, soft and beautifully scented.",
      brand: "Hemani",
      unit: "500ml",
      inStock: true,
      rating: 4,
      reviewCount: 78,
      reviews: [
        { name: "Farah Naz", date: "20 Oct 2024", rating: 4, comment: "Beautiful rose scent. Hands feel clean and soft." },
      ],
    },
    {
      id: 5,
      title: "Saeed Ghani Organic Rose Water Spray 120ml",
      price: "Rs. 166.50",
      oldPrice: "Rs. 185.00",
      image: "/home-sales-container-imges/Saeed Ghani Organic Rose Water Spray 120ml-5.webp",
      description: "100% organic rose water spray by Saeed Ghani. Refreshes skin, tones pores and gives instant hydration.",
      brand: "Saeed Ghani",
      unit: "120ml Spray",
      inStock: true,
      rating: 5,
      reviewCount: 310,
      reviews: [
        { name: "Ayesha Malik", date: "15 Oct 2024", rating: 5, comment: "Best rose water I have ever used. Smells divine!" },
        { name: "Saba Ahmad", date: "22 Oct 2024", rating: 5, comment: "Organic and pure. Great for skin refreshment." },
      ],
    },
    {
      id: 6,
      title: "Saeed Ghani Pure & Natural Coconut Hair Oil 200ml",
      price: "Rs. 414.00",
      oldPrice: "Rs. 460.00",
      image: "/home-sales-container-imges/Saeed Ghani Pure & Natural Coconut Hair Oil 200ml-6.webp",
      description: "Saeed Ghani Pure Coconut Hair Oil is cold-pressed and 100% natural. Deeply conditions and adds shine to hair.",
      brand: "Saeed Ghani",
      unit: "200ml",
      inStock: true,
      rating: 4,
      reviewCount: 185,
      reviews: [
        { name: "Maryam Javed", date: "8 Nov 2024", rating: 4, comment: "Good quality oil. Hair becomes very smooth." },
      ],
    },
    {
      id: 7,
      title: "Saeed Ghani Organic Rose Water Spray 120ml Special",
      price: "Rs. 414.00",
      oldPrice: "Rs. 460.00",
      image: "/home-sales-container-imges/Saeed Ghani Organic Rose Water Spray 120ml-5.webp",
      description: "Special edition Saeed Ghani Organic Rose Water Spray. Perfect for daily skincare routine.",
      brand: "Saeed Ghani",
      unit: "120ml Spray",
      inStock: false,
      rating: 4,
      reviewCount: 55,
      reviews: [
        { name: "Rida Shah", date: "3 Nov 2024", rating: 4, comment: "Nice product but currently hard to find in stock." },
      ],
    },
    {
      id: 8,
      title: "Saeed Ghani Pure & Natural Coconut Hair Oil 200ml Large",
      price: "Rs. 414.00",
      oldPrice: "Rs. 460.00",
      image: "/home-sales-container-imges/Saeed Ghani Pure & Natural Coconut Hair Oil 200ml-6.webp",
      description: "Large pack of Saeed Ghani Pure Coconut Hair Oil. Value for money and great for regular use.",
      brand: "Saeed Ghani",
      unit: "200ml",
      inStock: true,
      rating: 5,
      reviewCount: 120,
      reviews: [
        { name: "Kiran Asif", date: "11 Nov 2024", rating: 5, comment: "Great value pack. Love this oil!" },
      ],
    },
  ];