export const products = [
    {
      id: 1,
      title: "Cac-1000 Plus Effervescent Orange",
      price: "Rs. 330.00",
      oldPrice: "Rs. 350.00",
      image: "/products/pic-1.webp",
      description: "Vitamin C effervescent supplement with refreshing orange flavor. Helps boost immunity, energy levels and overall health.",
      brand: "Cac-1000",
      unit: "10 Tablets",
      inStock: true,
      rating: 4,
      reviewCount: 128,
      reviews: [
        { name: "Ahmed Ali", date: "12 Oct 2024", rating: 5, comment: "Very effective product. Highly recommended!" },
        { name: "Sara Khan", date: "5 Nov 2024", rating: 4, comment: "Good taste and works well." },
      ],
    },
    {
      id: 2,
      title: "Nutrilov Chocolate Brownie Granola Bar",
      price: "Rs. 210.00",
      image: "/products/pic-2.webp",
      description: "Delicious and healthy granola bar with rich chocolate brownie flavor. High in fiber and protein, perfect for a quick snack.",
      brand: "Nutrilov",
      unit: "60g Bar",
      inStock: true,
      rating: 4,
      reviewCount: 85,
      reviews: [
        { name: "Fatima Malik", date: "20 Oct 2024", rating: 4, comment: "Tasty and filling. Good for on-the-go." },
      ],
    },
    {
      id: 3,
      title: "Ponstan Oral Suspension 90ml",
      price: "Rs. 134.90",
      oldPrice: "Rs. 142.00",
      image: "/products/pic-3.png",
      description: "Mefenamic acid oral suspension for relief of mild to moderate pain including headache, dental pain and fever.",
      brand: "Pfizer",
      unit: "90ml Bottle",
      inStock: true,
      rating: 5,
      reviewCount: 210,
      reviews: [
        { name: "Dr. Usman", date: "1 Nov 2024", rating: 5, comment: "Works fast for fever and pain relief." },
        { name: "Hina Baig", date: "3 Nov 2024", rating: 4, comment: "Effective medicine, easy to give to kids." },
      ],
    },
    {
      id: 4,
      title: "Safety Examination Gloves Large",
      price: "Rs. 16.50",
      oldPrice: "",
      image: "/products/pic-4.webp",
      description: "Disposable latex-free, powder-free examination gloves. Suitable for medical and general use. Available in large size.",
      brand: "Safety",
      unit: "Pack of 100",
      inStock: false,
      rating: 3,
      reviewCount: 45,
      reviews: [
        { name: "Kamran Hussain", date: "10 Oct 2024", rating: 3, comment: "Decent quality for the price." },
      ],
    },
    {
      id: 5,
      title: "Folic Acid Tablets",
      price: "Rs. 101.00",
      oldPrice: "Rs. 105.80",
      image: "/products/pic-5.webp",
      description: "Essential folic acid supplement. Recommended during pregnancy to support healthy fetal development and prevent deficiencies.",
      brand: "Genome",
      unit: "30 Tablets",
      inStock: true,
      rating: 5,
      reviewCount: 320,
      reviews: [
        { name: "Ayesha Noor", date: "15 Oct 2024", rating: 5, comment: "Doctor recommended. Very helpful during pregnancy." },
        { name: "Saba Tariq", date: "22 Oct 2024", rating: 5, comment: "Good quality and affordable price." },
      ],
    },
    {
      id: 6,
      title: "Sert Tablets 50mg",
      price: "Rs. 427.90",
      oldPrice: "Rs. 450.39",
      image: "/products/pic-6.webp",
      description: "Sertraline HCl 50mg tablets. Prescribed medication for depression and anxiety disorders. Use strictly as directed by doctor.",
      brand: "GSK",
      unit: "14 Tablets",
      inStock: true,
      rating: 4,
      reviewCount: 67,
      reviews: [
        { name: "Anonymous", date: "8 Nov 2024", rating: 4, comment: "Effective when used as prescribed." },
      ],
    },
  ];